### ISSUE TITLE
Improve amqp connection health testing

### ISSUE THREAD

**Issue by aolivier** [valtech-sd/amqp-cacoon#13]
- Is there a good way for mocking connection loss in testing? 
- As of now, I manually tested reconnect / resending by starting and stopping an amqp docker, but maybe it could be mocked

See this group:
https://groups.google.com/g/rabbitmq-users/c/Eegzba39PD4

**Comment by EricWasTakenMJD** [comment]
Going to resolve this by just not testing this in our library. In fact, in the latest PR I'm working on now, all "real host" tests are removed, meaning we're just mocking everything. Why? We just want to test our stuff. We will assume that the underlying libraries are handling all the things they say they handle. Reconnection testing is a feature of the underlying node amqp connection manager, so we'll just not test that here.
